version: '3.3'
services:
  post_db:
    image: mongo:${mongo_version}
    volumes:
      - post_db:/data/db
    networks:
      - back_net:
          aliases:
            - post_db
    links:
      - ui
      - post
      - comment
  ui:
    #build: ./ui
    image: ${USERNAME}/ui:${ui_version}
    ports:
      - 9292:9292/tcp
    networks:
      - front_net:
          aliases:
            - ui
      - back_net:
          aliases:
            - ui
  post:
    #build: ./post-py
    image: ${USERNAME}/post:${post_version}
    networks:
      - back_net:
          aliases:
            - post
  comment:
    #build: ./comment
    image: ${USERNAME}/comment:${comment_version}
    networks:
      - back_net:
          aliases:
            - comment
  
volumes:
  post_db:
    
networks:
  front_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${network_front}
  back_net:
    driver: bridge
    ipam:
      driver: default 
      config:
        - subnet: ${network_back}
        # 10.0.2.0/24